version: '3.1'

# хранилища
volumes:
    pgdata:
        driver: local
services:
    web:
# при падении будет стараться подняться
        restart: always
# только свежий nginx
        image: nginx:latest
# слушает порт 8080
        expose:
          - 8080
# мапаем порт 80 на его 8080. Тогда сайт будет доступен по адресу localhost. Убедись, что порт у тебя не занят.
        ports:
          - "80:8080"
# монтируем только те директории, в которых лежит статика, т.к. nginx с динамикой не будет работать. Также директорию с логами и файл настройки, который мы подготовили.
        volumes:
            - ./cdn/static:/srv/www/cdn/static
            - ./cdn/media:/srv/www/cdn/media
            - ./cdn/logs:/srv/www/cdn/logs
            - ./docker/web:/etc/nginx/conf.d
# и nginx зависит от контейнера python. Т.е. python должен быть запущен первым
        depends_on:
            - django
    django:
        restart: always
# указываем откуда собирать образ
        build:
            context: .
            dockerfile: docker/django/Dockerfile
# монтируем директорию проекта
        volumes:
            - ./cdn:/srv/www/cdn
        expose:
          - 8000
        ports:
            - 8000:8000
# запускаем gunicorn
        command: "gunicorn -c gunicorn.py cdn.wsgi"

